- app/helpers/common/utility/context_helper.rb
- extensions/themes/default/navigation.rb
Make it so you can't tell from the active top menu that the page exists.
> hide existance of a page if it's not visible

- app/helpers/profile_helper.rb
- app/models/picture.rb
- app/models/picture/storage.rb
- test/integration/group_profile_test.rb
also - do not crash when editing profile with active banner
- display banner image in banner style
> bugfix: display banner properly

- config/environments/development.rb
- config/environments/production.rb
- lib/crabgrass/conf.rb
This way we can set it in /etc in production
> config: read log level from config if given

- lib/extends/i18n.rb
Sometimes translations miss the pluralization or use wrong interpoliation.
Let's still render a meaningful page in production never the less.
> recover from I18n::ArgumentErrors in Production

- app/controllers/assets_controller.rb
This occured on a staging server because the assets had not been synced completely.
No need to crash though. 404 is the proper error to return and we do not clutter
our logs with traces anymore.
Print a warning in the logs never the less.
> bugfix: 404 instead of a 500 for missing asset file

- app/views/pages/create/_new_form.html.haml
Not exactly the way i would like to do this... but for now strings are frozen.
> mark translation with bold group name as html_safe

- config/environments/production.rb
Also filter all kinds of terms from the logs that might exhibit private info.
> config: fetch some rails options from crabgrass config

- app/models/asset_extension/thumbnails.rb
nil will bomb out when escaped. I'd rather have a 404 link than a page that renders an error.
> meaningful guess for thumbnail url with undefined thumbnail type

- app/views/layouts/global/nav/_groups_menu.html.haml
- app/views/layouts/global/nav/_people_menu.html.haml
We pick the most active - but that order is confusing.
So now we sort them alphabetically
> Sort entities in top menu alphabetically

- app/controllers/pages/posts_controller.rb
the index redirect would trigger a template not found error
> Fix creating comments without javascript

- extensions/pages/asset_page/app/SCRATCH
- extensions/pages/rate_many_page/app/controllers/rate_many_possibles_controller.rb
- extensions/pages/survey_page/app/controllers/survey_page_controller.rb
- extensions/pages/survey_page/app/controllers/survey_page_response_controller.rb
We use error, warning, info and success helpers now
> fix 500 caused by flash_message_now

- app/controllers/me/posts_controller.rb
- test/functional/me/posts_controller_test.rb
- test/integration/private_message_test.rb
Fix for issue during creation of a new private message before the discussion was actually created. (mentioned in comments here https://github.com/riseuplabs/crabgrass-core/pull/265)
Additional integration test was added to prevent possible regressions in future.
> Private message before discussion fix

- app/controllers/groups/membership_requests_controller.rb
- test/functional/groups/membership_requests_controller_test.rb
Groups::MembershipRequestsController was referencing req when there
only is @req. Also lacked redirect so it tried to render missing partial
Added functional test.
> bugfix: fix request to remove user from group

- app/helpers/me/notices_helper.rb
- app/views/me/notices/_notice.html.haml
- test/functional/me/notices_controller_test.rb
Still log them but proceed so users can access their dashboard
> prevent /me crashes on invalid notices

- app/views/wikis/wikis/_show.html.haml
wiki.former is different for different users and even on each visit.
> don't cache the wiki diff flags

- db/migrate/20150810090844_add_index_by_delta_to_page_terms.rb
- db/schema.rb
This will speed up fetching only the delta=true records for indexing
> add index on delta column to page_terms

- Vagrantfile
- doc/INSTALL.md
- doc/development/vagrant.md
Hi @azul !
I dare to take the liberty to offer an automated development environment setup using Vagrant and Virtualbox.
Using this approach everybody could setup an reproducible environment isolated from the host system at resources level as well as without a necessity to pollute it with project related packages (just reinstalled Linux at my own laptop and don't want to have all the time running search engines and databases from different projects anymore :scream:).
Have tested the README steps on two machines with a basic Ubuntu installed - works fine!
For my opinion despite the fact that such approach requires a bit more powerful machine the steps are easy (specially for people who have Vagrant and Virtualbox already) and maybe will help to invite some more contributors or bring back …
> Vagrant integration

- app/models/user_extension/groups.rb
- app/stylesheets/layout/_top_menu.scss
- app/stylesheets/ui/_icons.scss
- app/stylesheets/ui/_ui_elements.scss
- app/views/layouts/global/nav/_boxes.html.haml
- app/views/layouts/global/nav/_groups_menu.html.haml
- app/views/layouts/section/_heading_with_info.html.haml
- app/views/me/notices/index.html.haml
the list is composed of mostly recently visited groups, alpha sorted, that the user is a member of, plus the parent groups for groups that have parents.
> add list of groups to the dashboard, and make the "Groups" dropdown the same.

- extensions/pages/task_list_page/app/helpers/task_list_page_helper.rb
- extensions/pages/task_list_page/app/views/tasks/_checkbox.html.haml
- test/fixtures/tasks.yml
plus a few display and fixture tweaks
> task tweaks: check completed tasks on deleted pages

- app/controllers/pages/participations_controller.rb
- test/integration/page_sidebar_test.rb
.save! returns true and not the record in question
> bugfix: fix 500 on changing user access to a page

- vendor/gems/riseuplabs-greencloth-0.1/greencloth.gemspec
We had a nested array for the list of files
discovered by @mightydread in #373
> bugfix: gemspec works with latest version of bundler

- doc/INSTALL.md
- lib/tasks/images.rb
using pathname properly.
prevent #376 in the future.
> bugfix: cg:images:update_css works without public/stylesheets
