riseuplabs/crabgrass-core

- config/locales/en/gallery.yml
we removed the audio feature for galleries in the core rework.
> i18n: remove audio related keys from gallery

- app/models/user.rb
- lib/tasks/upgrade.rake
- vendor/crabgrass_plugins/castle_gates/lib/castle_gates/castle/associations.rb
- vendor/crabgrass_plugins/castle_gates/lib/castle_gates/key.rb
Instead of fetching the castle for a key and then looking at its class for the gate_set we now constantize the castle_type.
When the keys of a castle are loaded we now detect the one with the appropriate holder_code instead of fetching it from the database.
We also allow for preloading public and private_profile
> performance: tweaks for user permission migration

- app/models/avatar.rb
- test/integration/group_settings_test.rb
So we set this in the model to work around the plural default.
This is because of a loong pending rails bug:
https://github.com/rails/rails/issues/1769
> bugfix: avatars always use a single resource

- app/controllers/wikis/base_controller.rb
- app/helpers/common/ui/form_helper.rb
- app/helpers/wikis/assets_helper.rb
- app/views/ui/form/_inline_radio_button.html.haml
- app/views/wikis/assets/_select_buttons.html.haml
- app/views/wikis/wikis/edit.js.rjs
Turned radio_buttons_tag into inline_radio_buttons:
* use a partial rather than joining tags together by hand.
This way no .html_safe is needed.
* wrap the radio_button in a label. This way we do not need an id for the label
and it's the default way for doing this kind of thing with bootstrap
> Fix wiki asset upload form markup

- app/assets/javascripts/crabgrass/autocomplete.js
- app/helpers/common/ui/entity_display_helper.rb
- app/views/pages/shares/_recipient.html.haml
- test/helpers/integration/javascript/autocomplete.rb
- test/integration/page_sidebar_test.rb
+ is a way to encode ' '. So it will be replaced by rails automagically.
So we have to encode it when sending the first request.
In the form it will be encoded anyway. So no need to replace it in the hidden input.
While we are at it... also display the display_name on top and in bold and the name below
I may have found a way to fix the annoying non determenistic autocomplete integration
test failure at the same time. One thing is for sure ' r' in the field will trigger
the first request to autocomplete - even if the thing we are looking for is already
seeded. So instead i now try to fill in the space first - to prevent the first char
from getting cut off and then fill in only the term to autocomplete.
> encode + in group names in share autocomplete

- app/controllers/common/application/rescue_errors.rb
- app/controllers/groups/home_controller.rb
- app/controllers/groups/pages_controller.rb
- app/permissions/groups/base_permission.rb
- extensions/themes/default/navigation.rb
- test/helpers/integration/page_records.rb
- test/integration/page_access_test.rb
You may still see the banner if a page of that group is accessible
> bugfix: do not show Home and Pages links for hidden groups

- app/controllers/entities_controller.rb
- app/models/unauthenticated_user.rb
- app/models/user_extension/users.rb
- test/functional/entities_controller_test.rb
So far these results were excluded because the client already had them.
Since preload occasionally fails these days this is a workaround to make the result
less problematic. If the preload did not happen normal autocomplete will still work.
> Include preloaded results in filtered autocomplete queries

- app/helpers/common/ui/layout_helper.rb
- app/views/layouts/global/_head.html.haml
make sure that content_for :dom_loaded does not get cached. It can lead to all
kinds of funny results.
Obviously we want to move this into all app javascript. But for now let's just
keep it here.
> stay on top of wiki pages - do not scroll to bottom

- app/controllers/common/application/tracking.rb
- app/controllers/groups/home_controller.rb
- app/controllers/people/home_controller.rb
- app/views/layouts/global/nav/_top_menus.html.haml
track visits to group and user home controllers for now
This should provide the last_visited data for the drop down menu for groups and users.
It requires the CronController#tracking_update_hourlies to be called regularly.
> remove caching of top menu and bring back tracking

- app/helpers/common/ui/entity_display_helper.rb
Do not alter options hash in link_to_user and link_to_group.
> fix links in requests

- app/helpers/common/ui/avatar_helper.rb
Here's the error from the logs:
```
ActionView::Template::Error (undefined method `edit_context_avatar_path' for #<#<Class:0x007fee262424c8>:0x007fee26222e48>):
15:       - r.info I18n.t(:descriptive_name_for_display)
16:     - f.row do |r|
17:       - r.label :icon.t
18:       - r.input avatar_field(@group.becomes Group)
19:     - f.heading :locale.t
20:     - f.row do |r|
21:       - r.label :language.t
app/helpers/common/ui/avatar_helper.rb:63:in `avatar_field'
app/views/groups/settings/show.html.haml:18:in `block (3 levels) in _app_views_groups_settings_show_html_haml___534312476661232484_70330409355620'
app/views/groups/settings/show.html.haml:16:in `block (2 levels) in _app_views_groups_settings_show_html_haml___534312476661232484_70330409355620' …
```
> debug output to fix NoMethodError in GroupSettings

- app/views/common/posts/default/_edit.html.haml
- test/integration/message_test.rb
the private post has to become a Post first so the field name matches our
expectations in the update action.
> fix editing private posts

- extensions/pages/wiki_page/test/integration/wiki_test.rb
- vendor/gems/riseuplabs-greencloth-0.1/lib/greencloth.rb
- vendor/gems/riseuplabs-greencloth-0.1/test/lite_mode_test.rb
- vendor/gems/riseuplabs-greencloth-0.1/test/markup_test.rb
- vendor/gems/riseuplabs-greencloth-0.1/test/outline_test.rb
Fixes issue introduced by ruby2:
respond_to? will return false for protected methods.
http://tenderlovemaking.com/2012/09/07/protected-methods-and-ruby-2-0.html
This lead to toc not getting rendered for wikis.
Also ported the greencloth tests to ruby2. Some of them are still failing
but it seems they also were before.
> bugfix: display toc for wikis

- .travis.yml
It seems we were not testing libreoffice functionality on travis anyway. At least the build is still green without it.
I will have to investigate both libreoffice and sphinx on travis and reduce the number of skipped tests.
But for now this makes travis so much faster so let's use container builds. :package:
> Use container builds on travis - much faster

- app/controllers/groups/groups_controller.rb
- app/models/committee.rb
- app/models/group.rb
- app/models/group_extension/groups.rb
- app/models/group_extension/users.rb
- app/models/mailers/group.rb
- app/models/observers/group_observer.rb
- test/unit/activity_test.rb
- test/unit/committee_test.rb
- test/unit/council_test.rb
- test/unit/group_test.rb
- test/unit/pagination_test.rb
- test/unit/permission_test.rb
- test/unit/request_test.rb
- test/unit/tracking_test.rb
Observers are getting deprecated and it's really hard to figure out that they even exist.
Use the power of rails to remember associations of destroyed objects rather than
trying to capture these associations in additional attributes.
Keed the default rails association methods like parent= and group.destroy and use inverse_of to make sure the associated objects stay in sync.
> rework group destruction to use rails powers

- app/helpers/wikis/base_helper.rb
- config/routes.rb
- extensions/pages/wiki_page/app/controllers/wiki_page_controller.rb
- extensions/pages/wiki_page/config/routes.rb
There's still a bunch of 404 from external links to this kind of url
> bring back the context/page/print url - at least for wikis

- test/functional/exceptions_controller_test.rb
This test uses Rack::Test::Methods because the exceptions controller is usually
triggered from the Crabgrass::PublicExceptions middleware.
> test exceptions controller

- Gemfile
- Gemfile.lock
- app/controllers/groups/home_controller.rb
- app/controllers/groups/pages_controller.rb
- test/test_helper.rb
- vendor/crabgrass_plugins/castle_gates/test/test.rb
- vendor/crabgrass_plugins/castle_gates/test/test_helper.rb
Also allow me to run the castle_gates tests with minitest 5.6 which I have installed and which is used when tests are run without bundle exec.
Also make castle gates tests independent of run order
> update test environment - minitest 4.7 and mocha 1.1

- extensions/themes/default/navigation.rb
Issue occurs because of the typo in the css class name
Bug: #9524
Link: https://labs.riseup.net/code/issues/9524
Just need to start from something simple :wink:
> Fix for tasks icon missed in the main menu

- Gemfile
Hi!
I have faced a problem when the Thin server was not installed on the system with `Ruby 2.1.5`. And it have blocked running the application on my local machine.
So this simple conditional was added to fix it.
Actually I believe that `Ruby 1.9` is not receiving security update anymore. Maybe it is worth to drop support for it?
One more question. I saw another one condition for similar problem, like this:
```ruby
if Bundler.respond_to?(:current_ruby) &&
Bundler.current_ruby.respond_to (:mri_21?)                                                                  
gem 'byebug', :platforms => [:mri_20, :mri_21]                                                              
end  
```
Is there special need to check the Ruby version through the Bundler rather than `RUBY_VERSION` constant?
In case …
> Update the Thin gem dependency for Ruby > 2

- app/controllers/common/posts.rb
- app/controllers/me/posts_controller.rb
- app/controllers/pages/posts_controller.rb
- app/views/common/posts/_list_as_default.html.haml
- app/views/common/posts/default/_reply_body.html.haml
- app/views/me/posts/index.js.rjs
- app/views/pages/posts/index.js.rjs
- config/routes.rb
- test/functional/pages/posts_controller_test.rb
We now use two controller actions ... one for generating the post and
then we redirect to one for rerendering the list of posts.
This way we can set @post to the created post in the creation action
and track it and have a new Post as @post in the index action.
> make comments and messages more robust

- app/models/asset_extension/upload.rb
- test/unit/asset_test.rb
Otherwise they end up breaking the entire page.
> make sure assets have a filename if upload aborts

- app/models/asset_extension/upload.rb
- extensions/pages/asset_page/test/unit/asset_page_test.rb
- test/unit/asset_test.rb
We're not using it and it adds quite a bit of complexity
> cleanup: remove direct data upload from assets

- app/models/discussion/discussion.rb
- test/unit/private_message_notice_test.rb
Hi!
Dismiss the private message notification for a reciever
if the message was deleted by a sender.
Do nothing if a reciever dissmissed it already.
Affects only private messages between users.
Feature: #8493
Link: https://labs.riseup.net/code/issues/8493
Maybe I missed something?
> Dismiss private message notification for deleted message

- app/assets/javascripts/crabgrass/upload/handleEvents.js
Issue description:
When user uploads an image to a gallery using the
Drag'n'Drop feature, upload occurs incrementally,
that leads to massive amount of duplicates in a gallery.
The fix is the replacing already assigned events on existent
DOM elements to prevent same events assigned each time
ajaxUpload reinitialized.
Bug: #9656
Link: https://labs.riseup.net/code/issues/9656
---
`ajaxUpload` reinitialized each time we upload the image. So usage of `addEventListener` adds event duplicates on form, that leads to problem mentioned above.
`inline` javascript event attachment replace existent ones, so we control it.
The sad story is how I debugged it until found the reason :sob:
And still not sure, maybe it is better just to prevent double reinitialization of `ajaxUpload`:
```bash …
```
> Fix for incremental images upload to a gallery with Drag'n'Drop

- app/models/page_history.rb
- test/helpers/integration/javascript/page_actions.rb
- test/helpers/integration/page_assertions.rb
- test/integration/page_sidebar_test.rb
The factory for PageHistories for these cases was broken.
class_for_update needs to be a class method.
> bugfix: turn pages public and private without error

- app/controllers/me/avatars_controller.rb
- app/helpers/common/ui/avatar_helper.rb
- app/views/me/settings/show.html.haml
- config/locales/en/me.yml
- config/routes.rb
- test/functional/me/avatars_controller_test.rb
Currently there is no way to remove the image
for avatar placed at `me/settings` section.
We can only replace it with another one.
This patch implements the possibility to completely
remove old avatar and have the the default icon come back.
Feature: 3292
Link: https://labs.riseup.net/code/issues/3292
Example how it looks like:
> Feature: Ability to remove account settings avatar

- app/controllers/people/friend_requests_controller.rb
- test/functional/people/friend_requests_controller_test.rb
If the user A requests the user B to be a contact
user B has no notification about it.
So the only way to approve - check the "Requests" tab manually.
Bug: 9675
Link: https://labs.riseup.net/code/issues/9675
---
The problem occurs because the `FriendRequestsController` does not implement `after_filter` for created requests.
Have fixed it by included common module for such functionality.
> Missed notification for contact request

- app/controllers/groups/invites_controller.rb
- app/models/notice/request_notice.rb
- test/functional/groups/invites_controller_test.rb
- test/unit/notice/request_notice_test.rb
Currently we have no notifications for such use-cases:
- group member invites new users to a group
- network group invites the group to join it
Bug: 9676
Link: https://labs.riseup.net/code/issues/9676
> Notifications for group invite are missed

- config/en.yml
- config/locales/de.yml
- config/locales/en/requests.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/nl.yml
- config/locales/no.yml
- config/locales/pl.yml
- config/locales/pt.yml
- lib/dummystrings.rb
When I invite a group A to join the network B, the members from this group A,
see an exception on `/me` page.
The exception description notices:
```ruby
I18n::MissingTranslationData: translation missing: en.request_to_join_our_network
```
It occurs because of the notification constructed for user with info about request to join network.
This issue related to the fixed issue [There is no notification for invite to join group](https://labs.riseup.net/code/issues/9676) / PR https://github.com/riseuplabs/crabgrass-core/pull/255, because before we have no such notifications at all..
So need to be tested only after [#9676](https://github.com/riseuplabs/crabgrass-core/pull/255) would be resolved and merged.
Bug: 9686
Link: https://labs.riseup.net/code/issues/9686
> Exception: Translation missed for network group invite notification

- app/controllers/assets_controller.rb
- test/functional/assets_controller_test.rb
- test/integration/asset_test.rb
We used some iso encoding before and that would turn some charectars into
%F3 and similar when url encoded.
Now that we switched to utf-8 some of those links still exist but lead to
utf-8 errors as characters above \xF0 are invalid. Since the exact filename
is not relevant for the assets controller anyway and this has been where we
saw the issue in production we will just drop the invalid chars in the utf-8
encoding.
> prevent 500 for links that still use url encodes iso chars

- app/controllers/wikis/wikis_controller.rb
- extensions/pages/wiki_page/test/integration/wiki_test.rb
- test/functional/wikis/wikis_controller_test.rb
Looks like before filters use a different set of formats for render.
They seem to default to html while the action itself would render js
just fine.
So cancel and submit without save buttons will be handled in #update
again. This way i don't have to worry about picking the right formatn.
> fix: canceling wiki edits renders wiki

- app/assets/javascripts/crabgrass/diff.js
There's no point in showing a diff where everything was added.
This is particularly important as it seems we did not save the
html_body of the wiki versions before.
> only show diff if old version was present

- app/helpers/people/base_helper.rb
- app/permissions/people_permission.rb
- app/views/people/home/_sidebox.html.haml
Hi!
Here is small feature implementation requested by WhilelM: ["Send message’ link from someone’s profil"](https://we.riseup.net/riseup+crabgrass/test-new-version-of-crabgrass#missing-features)
Description:
As user A who has rights to send a message to user B,
the link 'Send Message' should be displayed at user B profile page.
Placed under left side-bar, click leads to a new or existent discussion
page with selected user.
Have not added tests for it because permissions are already tested as part of `user_permission_test.rb` and I've wanted to minimize code duplication.
Seems that it would be good to create a `feature` in the labs tracker, or it is not necessary?
> Feature: Add "Send Message" link to a user profile

- app/controllers/common/posts.rb
- lib/extends/active_record.rb
- test/integration/message_test.rb
Fix for issue when user can not see the result of delete
action on private message until page reload.
It leads to exception if user would try to click the 'Delete'
button second time.
Issue: 9724
Link: https://labs.riseup.net/code/issues/9724
---
Changed hand-written AR method call into AS helper.
Actually AR method have formatted record into wrong selector. That is the reason why I have deleted it :sunglasses:
Of course I have checked that it used nowhere besides changed controller..
> Delete private message action does not hide it

- app/helpers/common/ui/post_helper.rb
- app/views/common/posts/default/_row.html.haml
Here is fix for one issue, related to comment date link and small feature implementation.
**Issue**: if we edit a comment that we own its date time becomes a link
that supposed show real time created/modification on click.
This functionality doesn't work at all, leads to javascript error in browser console.
**Feature**: now if I want to point somebody on some specific comment I could only note
the page where it is posted, but after user should go though all of the comments to find an appropriate.
It is not comfortable and decreases quoting possibilities if we want
share links to comments on external resources.
So I think that it might be useful.
Issue: #9729
Link: https://labs.riseup.net/code/issues/9729
Now each comment has anchor link ex. `http://xxxx/blue/multiply+1008#post-312` and …
> Anchor links for comments

- vendor/gems/riseuplabs-greencloth-0.1/lib/green_tree.rb
- vendor/gems/riseuplabs-greencloth-0.1/test/fixtures/sections.yml
- vendor/gems/riseuplabs-greencloth-0.1/test/markup_test.rb
A wiki with the same section names nested inside each other broke
redcloth because the heading regexp was to loose.
We do a depth first search for headings. Looking for the nested heading would then pick the parent heading with the old regexp. In particular we always searched for underlined headings even if the heading level was higher than 2 and no underlines were possible. We also searched for underlines with '==' and '--' no matter if the heading was an h1 or and h2.
This is now fixed so that only the proper underlines will match.
> bugfix: duplicate use of section names broke wiki

- app/models/requests/request.rb
- test/functional/groups/membership_requests_controller_test.rb
- test/functional/groups/requests_controller_test.rb
it lacked the event_attrs. We now define them for Request base class.
> bugfix: fix 500 when approving RequestToRemoveUser

- test/unit/assets/pdf_test.rb
- vendor/crabgrass_plugins/crabgrass_media/transmogrifiers/graphicsmagick.rb
It's way faster for large documents. If it fails we retry without setting the page.
You can use filename.pdf[0] in gm convert to only convert the first
page. This speeds up dealing with large documents a lot.
(.5 sec instead of 18 sec. for a 80 page, 7MB pdf i tried).
Rumors have it that some documents use letters for indexing their pages
and [0] won't work. So we need a fallback.
> try converting first page of pdf only

- app/models/assets/doc_asset.rb
- app/models/assets/image_asset.rb
- app/models/assets/spreadsheet_asset.rb
- app/models/assets/svg_asset.rb
- app/models/assets/text_asset.rb
- vendor/crabgrass_plugins/crabgrass_media/lib/media/transmogrifier.rb
- vendor/crabgrass_plugins/crabgrass_media/transmogrifiers/graphicsmagick.rb
For a single page super simple pdf that is about 8 times faster.
For a larger more complex one it's 20 times faster.
Also only look at the 0th page to determine page size. Huge speedup for
large pdfs. (15 sec -> 0.7 sec) for 80 page pdf.
> performance: create small jpgs from large ones

- app/helpers/common/ui/image_helper.rb
- app/helpers/pages/sidebar_helper.rb
- app/stylesheets/pages/_sidebar.scss
- test/helpers/integration/javascript/ajax_pending.rb
- test/helpers/integration/javascript/page_actions.rb
- test/integration/page_sidebar_test.rb
We recently discussed how browser based image scaling improved a lot throughout the last years.
Let's make use of this and fit the attachment previews into the sidebar.
Show one, two or three attachments per row in the sidebar - based on screen size:
> responsive attachment images in sidebar

- app/models/notice/notice.rb
- app/models/notice/post_starred_notice.rb
- test/unit/notice/post_starred_notice_test.rb
- test/unit/notice/private_message_notice_test.rb
I guess the post was removed by now. Need to be robust against this
anyway even though we should eventually remove all notices whose
noticables have been destroyed.
> fix: crash when trying to render notice without post

- app/helpers/wikis/sections_helper.rb
looks like utf-8 chars are now turned into _ - so we don't find the old sections
anymore.
> hotfix to work around changes in wiki section naming

- app/controllers/me/notices_controller.rb
Hi!
Here is small fix for N + 1 problem because not preloaded data at `me/index` action.
Only pages and notices was loaded in controller but deep in partials we had:
```ruby
url = self.send(notice.noticable_path, notice.noticable) # `noticable` association
```
```ruby
= link_to_entity(page.owner, avatar: :xsmall) # `owner` association
```
```ruby
= link_to_entity(page.updated_by, avatar: :xsmall)  # `updated_by` association aka user
```
Logs comparison https://gist.github.com/aliaksandrb/7fa318f10cce05446d50
The performance measures might be not so precise because was done locally and might be affected by other software was running at my laptop.
Maybe in future it would be great to setup kind of independent container for such testing, using `Vagrant` or `Docker` for example.. 
What do you …
> Homepage queries optimization

- app/controllers/people/directory_controller.rb
- test/functional/people/directory_controller_test.rb
Issue: 9735
Link: https://labs.riseup.net/code/issues/9735
---
In defect description @mcnair has also mentioned group directory, but it is alphabetized already.
Or maybe the note was about other places rather than just `*/people/directory` and `*/groups/directory` ?
> Show people directory entities alphabetized

- app/controllers/pages/posts_controller.rb
Here is simplest fix for feature requested by `@knister` > "After writing and sending a comment, page reloads but jumps back to the first page of comments, NOT to the page, where the comment had been posted. it’s not a big problem, but just kind of annoying." (https://we.riseup.net/riseup+crabgrass/test-new-version-of-crabgrass#recently-fixed)
It was reproduced only with Javascript disabled, just because anchor name is `#post-id` rather than `#posts-id`.
> Move to new comment after page reloaded

- app/helpers/wikis/sections_helper.rb
- app/models/wiki/decorator.rb
- extensions/pages/wiki_page/test/integration/wiki_test.rb
- test/helpers/integration/comments.rb
- test/helpers/integration/navigation.rb
- test/helpers/integration/wiki.rb
I tried to fix a bunch of issues that came up during wiki decoration lately.
Turns out i completely broke section editing in the end.
So to prevent this for the future we now have an integration test.
I also moved the bulk of the wiki decoration from the helper to a class of
its own - Wiki::Decorator. This way we can unit test the different issues
that come up instead of relying on integration tests.
> revert wiki decoration changes, move to class

- app/stylesheets/ui/_directory.scss
- app/views/groups/directory/_groups.html.haml
Here is small feature implementation, required here https://we.riseup.net/riseup+crabgrass/test-new-version-of-crabgrass#ease-of-use-clarity
maquis > "when I click on “see all groups” there is just a long list with no difference made between networks, groups, councils etc. Among other things, being able to distinguishing between the different types of groups would help people to find what they’re looking for."
A few screenshots how it looks like:
> Feature: Grouping for groups directory

- app/views/groups/home/_sidebox.html.haml
- app/views/wikis/wikis/_show.html.haml
The wiki/wiki/_show template is by far the one that takes most of the total
time spend rendering views.
This comes as no surprise as we not only insert the wiki.body_html but parse it
and extend it with the edit links and so on.
So instead of doing this all the time we now cache it based on the wiki (updated_at),
and the users locale if they are allowed to edit the wiki. The latter is necessary
for translating the wiki edit links and their titles.
> Cache wiki partial

- extensions/pages/asset_page/app/models/asset_page.rb
- extensions/pages/asset_page/test/unit/asset_page_test.rb
That's only when the page became public or nonpublic
> only update the asset symlinks when needed

- Gemfile
- Gemfile.lock
- app/models/page_terms.rb
- config/misc/schedule.rb
- db/migrate/20150810092223_add_queue_to_delayed_jobs.rb
- db/schema.rb
- doc/INSTALL.md
Thinking Sphinx will now create a delayed job for every indexing task.
This way the indexing will happen in a separate worker task and rails
can respond faster.
In order for this to work the delayed job tasks need to be run. That's
what the script/delayed_job script is for. You can start it as a daemon:
```
RAILS_ENV=production script/delayed_job start
```
Running the delta indexing asynchronous also reduces the need for
reindexing. The delta index may grow and delta indexing may be slow -
but it won't delay the response anymore.
Therefore this commit also sets the reindex frequency to 6 hours. Here's
the math behind this:
R denotes the time the reindex takes and d denotes the additional time
required by a doc in the delta index for a single index run. Then the
average index time per …
> Use thinking sphinxs delayed delta indexing

- app/controllers/cron_controller.rb
- config/misc/schedule.rb
The Rails.root path would have required a .to_s. But the whole
idea of running the rake task via system makes no sense in the
context of the CronController.
Instead we now use whenevers rake type.
rake ts:index takes 80 seconds total, 3 of those are for startup.
No point in blocking a passenger process for 80 seconds to avoid
the 3 second startup.
this superseeds pr #307 on github
> bugfix: make reindex cron action work

- app/controllers/cron_controller.rb
- config/misc/schedule.rb
There's no point in triggering a request with curl to then call
system from the controller.
Also... we want to keep fragment caches for more than just 3 days.
Currently we have about a month of caches and they occupy a total of
< 800MB. Many of them are probably page list entries and i bet they still are
used even if they have not been updated in a while.
> cron: drop cache cleanup tasks

- lib/generators/pagetype/USAGE
- lib/generators/pagetype/pagetype_generator.rb
- lib/generators/pagetype/templates/crabgrass_engine.rb.erb
- lib/generators/pagetype/templates/page.rb.erb
- lib/generators/pagetype/templates/page_controller.rb.erb
Description:
Create a new pagetype to use in crabgrass.
Running this generator will enable the creation of pages of a new type
inside crabgrass:
* Click on "Create New Page" in the 'me' menu.
* Pick the new pagetype - probably last in the selection
* fill in the fields for the page and create the page
This will create a page of the new pagetype. Of course the specific
functionality still needs to be added.
Example:
rails generate pagetype bird
This will create:
extensions/pages/bird_page
and preseed it with an engine, model and controller for the pagetype.
Inside the engine definition it will register the pagetype with
crabgrass and activate it in
config/crabgrass/crabgrass.development.yml
so it can be played with.
A dummy pagetype description will be added to
config/locales/en/pages.yml
> Generator for new pagetypes

- app/views/common/_asset_upload.html.haml
assigning a name to the upload-input handler will also submit the file
as a parameter for the given key. We add the file to the upload as the
`asset[uploaded_file]` with javascript so we end up uploading it for two
destinct keys and thus uploading it twice. :open_mouth:
> prevent duplicate asset upload

- app/controllers/cron_controller.rb
- config/misc/schedule.rb
We did not send them for a while and now we have a huge backlog.
So processing the backlog with the old routines has become impossible.
We used to load all page_histories into memory that had no notification send
and then process them. Currently these are > 1,000,000 records. So it eats
all mem and overwhelms the server.
> remove the notification cron tasks

- app/controllers/common/application/tracking.rb
- app/controllers/pages/before_filters.rb
- app/models/tracking/page.rb
- db/migrate/20150908105227_convert_to_innodb.rb
- db/schema.rb
- lib/extends/active_record.rb
- test/unit/pagination_test.rb
- test/unit/tracking/page_test.rb
InnoDB allows us to perform non blocking backups with transactions.
So we convert all the tables that remained as MyISAM tables to
InnoDB except page_terms which need the full text search capacities
that InnoDB only gained with mysql 5.6. (we're still on 5.5).
trackings were actively using "INSERT DELAYED" which also is
MyISAM specific - but will be removed in this commit as well.
The mysql docs say:
> Note that INSERT DELAYED is slower than a normal INSERT if the table
> is not otherwise in use.
So it very much looks like premature optimization.
The other tables just happen to still be MyISAM in production
> Use InnoDB for all tables but page_terms

- app/models/notice/page_update_notice.rb
- app/models/user_extension/pages.rb
- test/unit/notice/page_update_notice_test.rb
Hi!
This patch aims to reduce notifications that shown at user dashboard page.
We won't create a new one if there is already similar notification for page update (similar means it  that same page was update by same user), but update it's timestamp only.
References at labs:
Issue: #9415
Link: https://labs.riseup.net/code/issues/9415
Issue: #9738
Link: https://labs.riseup.net/code/issues/9738
This might me just only the first part of featured notifications noise reducing plan.
At least from personal perspective I see no sense to show notification for pages updates by myself.
Another one proposal was related to special notice title in case if one page was updated by a few persons. This is tricky, because currently track only the notice owner user, so title like:
"user **red** and **5** other …
> Less noisy page notifications at dashboard page

- extensions/themes/riseup/init.rb
:art: The default link color of #00e is very intense. It looks bad in
large headings because it breaks the overall color scheme.
This color is taken from the menu background in the banner navigation.
(banner background with a dark overlay)
It works both for normal fonts and for headings:
( I turned the heading into a link for testing - but that is not what i am planning - no worries. :sweat_smile: )
> default link color that can be used in headings

- app/controllers/me/tasks_controller.rb
- app/views/me/tasks/_page.html.haml
- app/views/me/tasks/index.html.haml
- extensions/pages/task_list_page/app/models/task_list_page.rb
- extensions/pages/task_list_page/test/unit/task_list_page_test.rb
Task Summary rework... Tasks often only make sense in the context of their pages. It's nice to have short task titles such as 'cleanup' without having to specify the context. However we currently only display the task name - not the page name in my tasks. So I propose to group tasks by pages instead.
> Group tasks by pages on the "my tasks" view

- app/stylesheets/ui/_wiki.scss
They were not displayed because we set list-style both for
ul and ol. Ordered lists should have their own list style though.
> bugfix: ordered list numbers in wikis

- extensions/pages/task_list_page/app/models/task_list_page.rb
For relations handed to TaskListPage.with_tasks we first build the task_ids.
Using the relation in the where clause will result in a subselect with a
join that makes for a very slow query.
> performance: speed up my tasks query

- app/controllers/me/tasks_controller.rb
- test/fixtures/task_participations.yml
- test/integration/task_overview_test.rb
Also an initial integration test to make sure the right tasks and
pages are displayed
> hide deleted pages and their tasks in me/tasks

- app/controllers/pages/before_filters.rb
- lib/crabgrass/conf.rb
the only thing that turning off tracking does is make it so that we can't sort a user's list of groups or users by order of most interactions.
the idea behind making tracking optional is that we might not want to retain information on the behavior of users. but disabling tracking only makes it so that we don't know what the owner of pages were that you have interacted with, but we still record that you interacted with those pages.
so, i think it is a very minor privacy gain to disable tracking, and currently it breaks some core functionality.
> enable `current_site.tracking?` by default.

- app/models/wiki_lock.rb
This lead to deadlocks with mysql.
Instead we simply remove the locks from the instance attributes.
> bugfix: don't save wiki lock record during find

- app/controllers/cron_controller.rb
This way we can respond quickly and still benefit from the already
running instances - in contrast to a rake task.
> use delayed job for long running CronController action

- app/views/session/_login_form.html.haml
- test/integration/error_flow_test.rb
Rebuilding the url may not be possible from params. In particular if
a dispatch controller jumped in and altered the params.
Instead we now use the exact string thatwe started from.
> bugfix: redirect url based on request not params

- app/controllers/theme_controller.rb
- app/views/theme/show.css.erb
rails 4 drops page caches and it does not work in production right now because
the corresponding apache config settings are missing.
> use fragment instead of page caching for themes screen.css

- app/controllers/theme_controller.rb
- app/views/theme/show.css.erb
- vendor/crabgrass_plugins/crabgrass_theme/lib/crabgrass/theme/cache.rb
Also use proper caching key.
Now we use them all:
* page cache - it's the fastest and makes it so only a small percentage of the css requests end up hitting the rails app.
* stale? - if the theme is the same the browser fetched the last time - and if it's the same file - just return a 304.
* fragment caching - for the first time visiting browsers cache the css in fragment cache.
> make use of 304 - not modified for css

- config/initializers/etags-flexibility.rb
This gives us the more flexible handling of etags from rails4
plus a fix for https://github.com/rails/rails/issues/19056
Resulting in 304 responses for the screen.css in firefox.
So the css does not need to be transfered anymore which cuts of
~ 200ms for every page rendering on the client for me.
> match etags with -gzip attached

- app/controllers/theme_controller.rb
- app/stylesheets/ui/_wiki.scss
- app/views/theme/show.css.erb
- config/directories.rb
The padding was to small to display two digit numbered lists. Now we should be fine even for three digits.
> enough padding for numbered lists in wikis

- app/models/group_extension/users.rb
- app/views/groups/_list_with_committees.html.haml
- app/views/groups/structures/_show_in_sidebar.html.haml
- app/views/me/notices/index.html.haml
- app/views/people/home/_friends.html.haml
- app/views/people/home/_groups.html.haml
- config/locales/en/groups.yml
Now we only display visible groups and users in the friends and group lists.
Also sorting groups by the ones one shares with the user in question and the
public ones.
Lists that can be sorted alphabetically in a meaningful way get sorted.
> alphabetic list of visible entities in sidebars

- app/controllers/groups/home_controller.rb
We already counted visits to group pages. But that probably is only
halve the truth.
> count all visits to the group landing page

- app/models/page.rb
- app/models/user_extension/cache.rb
- app/views/common/pages/_page_table_row.html.haml
- app/views/session/_login_form.html.haml
- app/views/wikis/wikis/_show.html.haml
- test/fixtures/group_participations.yml
- test/fixtures/page_terms.yml
- test/fixtures/pages.yml
- test/functional/people/home_controller_test.rb
- test/helpers/integration/enhanced_logging.rb
- test/integration/group_settings_test.rb
- test/unit/page/search_test.rb
Cache keys of page listings need to change if the owners name changes. Also there is no need to include a duplicate timestamp (one for the page.update_at and one for the formatted date).
So now we only use the formatted date and the page.uri - which includes the owner_name and the page name.
> ensure changed group names do not lead to broken links

- Gemfile
- Gemfile.lock
- app/models/picture/storage.rb
* the file extension should be seperated by a .
* crabgrass_media 0.0.4 fixes a bug where ENOENT was raised
after the conversion of a file failed.
> Fix picture upload issues, update crabgrass_media

- app/controllers/common/application/rescue_errors.rb
- test/helpers/integration/account_management.rb
- test/integration/group_invite_test.rb
It looks like we only print the error messages for js errors in debug level.
Raising to warn.
Also added a test for accepting an invite that came via email as a user
who already has an account.
> debug: approving invites via email can result in 500

- app/models/wiki.rb
- app/models/wiki_extension/sections.rb
- app/models/wiki_extension/versioning.rb
- app/permissions/wikis_permission.rb
- extensions/pages/wiki_page/test/functional/wikis/versions_controller_test.rb
- extensions/pages/wiki_page/test/integration/wiki_test.rb
- test/functional/wikis/versions_controller_test.rb
- test/helpers/wiki_test_helper.rb
- test/unit/wiki/locking_test.rb
- test/unit/wiki/section_locking_version_test.rb
- test/unit/wiki/versioning_test.rb
- test/unit/wiki_test.rb
This is an attempt to fix the failing test for #310.
One test was failing because the version setup did not work anymore. Instead of 6 versions it would create 5 as it tried to create two versions as the same user.
I also rewrote a different test which i used to track the problem down.
I also rewrote Wiki#create_new_version? a bit. It still does the same.
I found the old code hard to grasp - i hope this is a bit more clear.
> Feature/wikiversion - fix test for #310

- app/views/pages/assets/create.js.rjs
- test/integration/page_creation_test.rb
The url for the sortable_element was wrong. It would also render the collection of images in a wrong order.
We now work around the latter by using @page.images if it's available
(gallery) rather than @page.assets (other page types). images are sorted
by position based on showing wheras assets are not sorted right now.
The longer term fix for this will be to add a position field to the
assets and remove the showings table all together (we don't allow
reusing images across galeries for a long time now.)
> bugfix: sortable image list after file upload

- app/controllers/groups/structures_controller.rb
- test/functional/groups/structures_controller_test.rb
We used to create the committee before adding it to the parent.
So if a naming conflict turned up we already had created the record.
Now we just build the committee and it will be saved in
Group#add_committee!
for the first time.
> bugfix: fix committee creation - ensure parent

- app/controllers/assets_controller.rb
- app/models/asset_extension/storage.rb
Before we tested for the existance of the file and tried to symlink the
directory if it did not exist. Then we would redirect to the same url
assuming this fixed things.
Turns out that if there is a different issue such as the file missing -
not the symlink to the dir this does not fix thigns but leads to endless
redirects.
So now we only attempt to fix things by symlinking if there was no symlink
yet.
> only create a symlink for public asset dirs if needed

- app/models/mailer/page_histories.rb
- app/models/page_history.rb
- app/views/mailer/page_histories/_page.text.erb
- app/views/mailer/page_histories/_paranoid.text.erb
- app/views/mailer/page_histories/digest.text.erb
- config/locales/en/emails.yml
The mailer is called Mailer::PageHistories so it does not interfere
with the PageHistory toplevel class.
Also... a number of i18n keys were messed up.
> bugfix: fix page updates mailer, i18n keys

- app/views/groups/structures/_show_in_sidebar.html.haml
We would also have to expire the cache every time a link or a name changes.
This boils down to
cache @group, @group.committees.count, @group.committees.max(:updated_at), ... do
Currently rendering the corresponding lists is not really slow - 20 ms. for all the
entities of animals.
So if we have to query every association for it's size and the max updated at
we probably won't gain much and this kind of caching is error prone.
> bugfix: remove caching of page entities
